### ISSUE TITLE
why

### ISSUE THREAD

**Issue by xfnty** [p3nguin-kun/christmas-bspwm-dotfiles#1]
https://github.com/p3nguin-kun/christmas-bspwm-dotfiles/blob/ff7fe471752d8c40530c3cb9794c2eda8d4ec15e/themes/dark/index.theme#L4
anyway just delete this issue if u want

**Comment by p3nguin-kun** [comment]
i don't know about this thing, i just use themix to create gtk theme.

**Comment by p3nguin-kun** [comment]
btw, i'll delete it.

**Comment by p3nguin-kun** [comment]
edited.
